// This file is auto generated by YIZY API, do not modify.
// Instead, update your API specification and upload it to yizy.dev/app to regenerate this file!
export interface YizyError {
  code: number;
  msg: string;
}

export interface LoginResult {
  token: string;
}

export interface LoginRequest {
  email: string;
}

export interface LoginResponse {
  error: YizyError | null;
  result: LoginResult | null;
}

export async function login(
  req: LoginRequest,
  headers?: Record<string, string>,
): Promise<LoginResponse> {
  let defaultHeaders = {
    "Content-Type": "application/json",
  };

  if (headers) {
    defaultHeaders = { ...defaultHeaders, ...headers };
  }

  const response = await fetch("http://localhost:5173/api/auth/login", {
    method: "POST",
    headers: defaultHeaders,
    body: JSON.stringify(req),
    credentials: "include",
  });

  const result: LoginResponse = await response.json();
  return result;
}
