export const generatorWarning =
  "// This file is auto generated by YIZY API, do not modify.\n// Instead, update your API specification and upload it to yizy.dev/app to regenerate this file!\n";

export function getGeneratorComments(version: string, serviceName: string) {
  const content = `
// This file is generated with ${serviceName} Spec version ${version}.
// This file is auto generated by YIZY API, do not modify.
// You can update and regenerate this file by visiting https://yizy.dev/demo or https://yizy.dev/app

`;
  return content;
}
