export const generatorWarning =
  "// This file is auto generated by YIZY API, do not modify.\n// Instead, update your API specification and upload it to yizy.rootxsnowstudio.com/app to regenerate this file!\n";
