openapi: 3.0.3
info:
  title: SecretService
  description: This is a generated API Spec
  version: This is a generated API Spec
servers:
  - url: http://localhost:8080
paths:
  /agents/getAgentByName:
    post:
      operationId: getAgentByName
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetAgentByNameRequest'
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAgentByNameResponse'
          description: default response
components:
  schemas:
    GetAgentByNameRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    GetAgentByNameResponse:
      type: object
      required:
        - error
        - agent
      properties:
        error:
          nullable: true
          $ref: '#/components/schemas/Grenade'
        agent:
          $ref: '#/components/schemas/Agent'
    Agent:
      type: object
      required:
        - name
        - age
        - department
      properties:
        name:
          type: string
        age:
          type: integer
        department:
          type: string
    Grenade:
      type: object
      required:
        - code
        - msg
        - name
      properties:
        code:
          type: integer
        msg:
          type: string
        name:
          type: string
